/*
 *     SPDX-License-Identifier: AGPL-3.0-only
 *
 *     Copyright (C) RainbowDashLabs and Contributor
 */
package dev.chojo.ember.feature.signing.service;

import dev.chojo.ember.api.refusal.RefusalResponse;
import dev.chojo.ember.feature.events.entity.EventRegistration;
import dev.chojo.ember.feature.events.entity.StationEvent;
import dev.chojo.ember.feature.events.repository.EventRegistrationRepository;
import dev.chojo.ember.feature.events.repository.EventRepository;
import dev.chojo.ember.feature.generator.entity.DocumentTemplate;
import dev.chojo.ember.feature.generator.entity.PaperState;
import dev.chojo.ember.feature.generator.entity.PaperSubmission;
import dev.chojo.ember.feature.generator.entity.RequirementGeneration;
import dev.chojo.ember.feature.generator.repository.EventRequirementRepository;
import dev.chojo.ember.feature.generator.repository.PaperSubmissionRepository;
import dev.chojo.ember.feature.generator.service.AppointmentDocumentService;
import dev.chojo.ember.feature.signing.entity.AppointmentRequest;
import dev.chojo.ember.feature.signing.repository.SignatureRequestRepository;
import jakarta.inject.Inject;
import jakarta.inject.Singleton;
import org.jspecify.annotations.Nullable;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.time.LocalDate;
import java.util.HashSet;
import java.util.List;
import java.util.Objects;
import java.util.Set;
import java.util.stream.Collectors;

/**
 * Asks for the signatures of the documents an appointment asks its participants to bring, as a member takes
 * a place on one of its dates, and withdraws what is still open once they give it up.
 *
 * <p>Taking a place, pending or accepted, by any way a registration is written: the member or a guardian
 * registering with or without the appointment's questions, a manager registering them, a manager accepting
 * a pending one, or a withdrawal taken back. For every document the appointment asks for whose copy asks
 * the member or a guardian to sign, the member's copy for the date is generated and filed with them (the
 * current copy is used again where one is filed) and its signatures are asked for. Nothing is asked again
 * for a document whose signatures were already asked for on the date, or whose signed paper copy was
 * confirmed. The copy is generated by whoever registered the member.
 *
 * <p>Giving the place up (withdrawn, declined, turned down) withdraws every signature still open on the
 * member's copies for the date; signed fields stay.
 *
 * <p>A document that cannot be generated or asked for, such as at a station that keeps no documents, is
 * logged and left out, and the registration stands.
 */
@Singleton
public class AppointmentSignatures {
    private static final Logger log = LoggerFactory.getLogger(AppointmentSignatures.class);

    private final EventRepository events;
    private final EventRegistrationRepository registrations;
    private final AppointmentDocumentService appointments;
    private final EventRequirementRepository copies;
    private final PaperSubmissionRepository scans;
    private final SignatureRequestRepository requests;
    private final SignatureRequestService requestService;

    @Inject
    public AppointmentSignatures(
            EventRepository events,
            EventRegistrationRepository registrations,
            AppointmentDocumentService appointments,
            EventRequirementRepository copies,
            PaperSubmissionRepository scans,
            SignatureRequestRepository requests,
            SignatureRequestService requestService) {
        this.events = events;
        this.registrations = registrations;
        this.appointments = appointments;
        this.copies = copies;
        this.scans = scans;
        this.requests = requests;
        this.requestService = requestService;
    }

    /**
     * Asks for the signatures of the documents the appointment asks the member to bring on the date, where
     * the member holds a place on it.
     *
     * @param eventId  the appointment
     * @param date     the date
     * @param memberId the member who took a place
     * @return how many documents were asked for now
     */
    public int askOnRegistration(int eventId, LocalDate date, int memberId) {
        var event = events.findById(eventId).orElse(null);
        var registration = event == null ? null : placeOf(eventId, date, memberId);
        if (event == null || registration == null) return 0;
        var signable = appointments.signableFor(event, memberId);
        if (signable.isEmpty()) return 0;
        var settled = settledTemplates(eventId, date, memberId);
        var filed = copies.latest(eventId, date, List.of(memberId));
        int generatedBy = Objects.requireNonNullElse(registration.createdBy(), memberId);
        int asked = 0;
        for (var template : signable) {
            if (settled.contains(template.id())) continue;
            try {
                ask(event, date, template, memberId, generatedBy, currentCopy(filed, template));
                asked++;
            } catch (RuntimeException e) {
                log.warn(
                        "Could not ask for the signatures of template {} for member {} at appointment {} on {}",
                        template.id(),
                        memberId,
                        eventId,
                        date,
                        e);
            }
        }
        return asked;
    }

    /**
     * Withdraws every signature still open on the member's copies for the date, once they no longer take
     * part.
     *
     * @param eventId  the appointment
     * @param date     the date
     * @param memberId the member who gave their place up
     * @return how many requests were withdrawn
     */
    public int withdrawOnLeaving(int eventId, LocalDate date, int memberId) {
        if (placeOf(eventId, date, memberId) != null) return 0;
        return requestService.withdrawForAppointment(eventId, date, memberId);
    }

    /** The member's registration for the date where it holds a place, pending or accepted, else null. */
    private @Nullable EventRegistration placeOf(int eventId, LocalDate date, int memberId) {
        if (!registrations.findRegisteredMemberIds(eventId, date).contains(memberId)) return null;
        return registrations.findByEventAndDate(eventId, date).stream()
                .filter(registration -> registration.memberId() == memberId)
                .findFirst()
                .orElse(null);
    }

    /** The documents nothing is asked for again: signatures already asked for, or the paper copy confirmed. */
    private Set<Integer> settledTemplates(int eventId, LocalDate date, int memberId) {
        var settled = requests.liveForAppointment(eventId, date, memberId).stream()
                .map(AppointmentRequest::templateId)
                .collect(Collectors.toCollection(HashSet::new));
        scans.latest(eventId, date, List.of(memberId)).stream()
                .filter(scan -> scan.state() == PaperState.CONFIRMED)
                .map(PaperSubmission::templateId)
                .forEach(settled::add);
        return settled;
    }

    private static @Nullable RequirementGeneration currentCopy(
            List<RequirementGeneration> filed, DocumentTemplate template) {
        return filed.stream()
                .filter(copy -> copy.templateId() == template.id() && copy.templateVersion() >= template.version())
                .findFirst()
                .orElse(null);
    }

    /**
     * Asks on the current copy where one is filed and still asks for signatures as it was generated, else on
     * a copy generated now.
     */
    private void ask(
            StationEvent event,
            LocalDate date,
            DocumentTemplate template,
            int memberId,
            int generatedBy,
            @Nullable RequirementGeneration copy) {
        if (copy != null) {
            try {
                requestService.requestForAppointment(copy.generationId());
                return;
            } catch (RefusalResponse e) {
                log.info(
                        "Copy {} of template {} cannot be asked on ({}), generating a new one",
                        copy.documentId(),
                        template.id(),
                        e.refusal());
            }
        }
        var generated = appointments.generateFor(event, date, template, memberId, generatedBy);
        requestService.requestForAppointment(generated.generationId());
    }
}
