/*
 *     SPDX-License-Identifier: AGPL-3.0-only
 *
 *     Copyright (C) RainbowDashLabs and Contributor
 */
package dev.chojo.ember.feature.signing.service;

import dev.chojo.ember.api.refusal.RefusalResponse;
import dev.chojo.ember.feature.events.entity.EventRegistration;
import dev.chojo.ember.feature.events.entity.RegistrationStatus;
import dev.chojo.ember.feature.events.entity.StationEvent;
import dev.chojo.ember.feature.events.repository.EventRegistrationRepository;
import dev.chojo.ember.feature.events.repository.EventRepository;
import dev.chojo.ember.feature.generator.entity.DocumentTemplate;
import dev.chojo.ember.feature.generator.entity.PaperState;
import dev.chojo.ember.feature.generator.entity.PaperSubmission;
import dev.chojo.ember.feature.generator.entity.RequirementGeneration;
import dev.chojo.ember.feature.generator.repository.DocumentGenerationRepository;
import dev.chojo.ember.feature.generator.repository.EventRequirementRepository;
import dev.chojo.ember.feature.generator.repository.PaperSubmissionRepository;
import dev.chojo.ember.feature.generator.service.AppointmentDocumentService;
import dev.chojo.ember.feature.signing.entity.AppointmentCopy;
import dev.chojo.ember.feature.signing.entity.AppointmentRequest;
import dev.chojo.ember.feature.signing.repository.IssuerSignatureRepository;
import dev.chojo.ember.feature.signing.repository.SignatureRequestRepository;
import jakarta.inject.Inject;
import jakarta.inject.Singleton;
import org.jspecify.annotations.Nullable;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.time.LocalDate;
import java.util.Collection;
import java.util.HashSet;
import java.util.List;
import java.util.Objects;
import java.util.Set;
import java.util.function.Predicate;
import java.util.stream.Collectors;

/**
 * Asks for the signatures of the documents an appointment asks its participants to bring, as a member takes
 * a place on one of its dates, and withdraws what is still open once they give it up.
 *
 * <p>Taking a place, pending or accepted, by any way a registration is written: the member or a guardian
 * registering with or without the appointment's questions, a manager registering them, a manager accepting
 * a pending one, or a withdrawal taken back. For every document the appointment asks for whose copy asks
 * the member or a guardian to sign, the member's copy for the date is generated and filed with them (the
 * current copy is used again where one is filed) and its signatures are asked for. Nothing is asked again
 * for a document whose signatures were already asked for on the date, or whose signed paper copy was
 * confirmed. The copy is generated by whoever registered the member.
 *
 * <p>The issuer's field signs itself where it can: a copy is generated with the issuer's signature where the
 * template's issuer agreed to letters being signed for them ({@link IssuedLetterSigner}), so the station's
 * part is done when the signatures are asked for and only the member side remains. A copy filed earlier
 * without it, while the issuer would sign it now, is generated again rather than asked on.
 *
 * <p>Giving the place up (withdrawn, declined, turned down) withdraws every signature still open on the
 * member's copies for the date; signed fields stay. On an appointment that takes no registrations nobody
 * holds a place: its agreements are offered on its page ({@link #askAgreement}), and only saying they will
 * not come withdraws what is still open, while taking that back does not.
 *
 * <p>A document that cannot be generated or asked for, such as at a station that keeps no documents, is
 * logged and left out, and the registration stands.
 */
@Singleton
public class AppointmentSignatures {
    private static final Logger log = LoggerFactory.getLogger(AppointmentSignatures.class);

    private final EventRepository events;
    private final EventRegistrationRepository registrations;
    private final AppointmentDocumentService appointments;
    private final EventRequirementRepository copies;
    private final PaperSubmissionRepository scans;
    private final SignatureRequestRepository requests;
    private final SignatureRequestService requestService;
    private final DocumentGenerationRepository generations;
    private final IssuerSignatureRepository issuerSignatures;
    private final IssuedLetterSigner letterSigner;

    @Inject
    public AppointmentSignatures(
            EventRepository events,
            EventRegistrationRepository registrations,
            AppointmentDocumentService appointments,
            EventRequirementRepository copies,
            PaperSubmissionRepository scans,
            SignatureRequestRepository requests,
            SignatureRequestService requestService,
            DocumentGenerationRepository generations,
            IssuerSignatureRepository issuerSignatures,
            IssuedLetterSigner letterSigner) {
        this.events = events;
        this.registrations = registrations;
        this.appointments = appointments;
        this.copies = copies;
        this.scans = scans;
        this.requests = requests;
        this.requestService = requestService;
        this.generations = generations;
        this.issuerSignatures = issuerSignatures;
        this.letterSigner = letterSigner;
    }

    /**
     * Asks for the signatures of the documents the appointment asks the member to bring on the date, where
     * the member holds a place on it.
     *
     * @param eventId  the appointment
     * @param date     the date
     * @param memberId the member who took a place
     * @return how many documents were asked for now
     */
    public int askOnRegistration(int eventId, LocalDate date, int memberId) {
        return askFor(eventId, date, memberId, template -> true);
    }

    /**
     * Asks for the signatures of documents the appointment asks for since the member took a place on the
     * date, the same way as on registering.
     *
     * @param eventId     the appointment
     * @param date        the date
     * @param memberId    the member holding a place
     * @param templateIds the documents added
     * @return how many documents were asked for now
     */
    public int askForAdded(int eventId, LocalDate date, int memberId, Collection<Integer> templateIds) {
        return askFor(eventId, date, memberId, template -> templateIds.contains(template.id()));
    }

    /**
     * Asks for the signatures of the documents the appointment asks the member to bring on the date that the
     * filter lets through, where the member holds a place on it.
     */
    private int askFor(int eventId, LocalDate date, int memberId, Predicate<DocumentTemplate> wanted) {
        var event = events.findById(eventId).orElse(null);
        var registration = event == null ? null : placeOf(eventId, date, memberId);
        if (event == null || registration == null) return 0;
        var signable = appointments.signableFor(event, memberId).stream()
                .filter(wanted)
                .toList();
        if (signable.isEmpty()) return 0;
        var settled = settledTemplates(eventId, date, memberId);
        var filed = copies.latest(eventId, date, List.of(memberId));
        int generatedBy = Objects.requireNonNullElse(registration.createdBy(), memberId);
        int asked = 0;
        for (var template : signable) {
            if (settled.contains(template.id())) continue;
            try {
                ask(event, date, template, memberId, generatedBy, currentCopy(filed, template));
                asked++;
            } catch (RuntimeException e) {
                log.warn(
                        "Could not ask for the signatures of template {} for member {} at appointment {} on {}",
                        template.id(),
                        memberId,
                        eventId,
                        date,
                        e);
            }
        }
        return asked;
    }

    /**
     * Withdraws every signature still open on the member's copies for the date, once they no longer take
     * part.
     *
     * @param eventId  the appointment
     * @param date     the date
     * @param memberId the member who gave their place up
     * @return how many requests were withdrawn
     */
    public int withdrawOnLeaving(int eventId, LocalDate date, int memberId) {
        var event = events.findById(eventId).orElse(null);
        boolean leaving = event == null || event.requiresRegistration()
                ? placeOf(eventId, date, memberId) == null
                : refused(eventId, date, memberId);
        if (!leaving) return 0;
        return requestService.withdrawForAppointment(eventId, date, memberId);
    }

    /**
     * Withdraws the confirmed scan of a participant's document for the date along with the agreement it was
     * confirmed for, so it no longer settles the document and a new scan can be handed in. A scan that does
     * not stand confirmed is left as it is.
     *
     * @param copy the participant's copy whose agreement was withdrawn
     */
    public void withdrawPaper(AppointmentCopy copy) {
        if (scans.withdrawConfirmed(copy.eventId(), copy.eventDate(), copy.templateId(), copy.memberId())) {
            log.info(
                    "Confirmed scan of template {} for member {} at appointment {} on {} withdrawn with its agreement",
                    copy.templateId(),
                    copy.memberId(),
                    copy.eventId(),
                    copy.eventDate());
        }
    }

    /**
     * Asks again for the signatures of a document whose agreement a signer withdrew, on a copy generated now,
     * where the member still holds a place on the date. The withdrawn copy is never asked on again: its
     * versions carry the signatures and the withdrawal.
     *
     * @param eventId    the appointment
     * @param date       the date
     * @param memberId   the member
     * @param templateId the document
     * @return whether it was asked for again
     */
    public boolean askAnew(int eventId, LocalDate date, int memberId, int templateId) {
        var event = events.findById(eventId).orElse(null);
        var registration = event == null ? null : placeOf(eventId, date, memberId);
        if (event == null || registration == null) return false;
        var template = appointments.signableFor(event, memberId).stream()
                .filter(candidate -> candidate.id() == templateId)
                .findFirst()
                .orElse(null);
        if (template == null) return false;
        ask(event, date, template, memberId, Objects.requireNonNullElse(registration.createdBy(), memberId), null);
        return true;
    }

    /**
     * Asks for the signatures of one document the appointment asks the member to bring on the date, on the
     * copy filed for the date where it can still be asked on, else on a copy generated now. Nothing is asked
     * where its signatures already stand asked for or signed on a copy for the date.
     *
     * @param event       the appointment
     * @param date        the date
     * @param template    the document, one the appointment asks the member side to sign
     * @param memberId    the member
     * @param generatedBy who a new copy is generated by
     * @return the request that stands for it, new or as it was
     */
    public AppointmentRequest askAgreement(
            StationEvent event, LocalDate date, DocumentTemplate template, int memberId, int generatedBy) {
        var live = liveFor(event.id(), date, memberId, template.id());
        if (live != null) return live;
        var filed = copies.latest(event.id(), date, List.of(memberId));
        ask(event, date, template, memberId, generatedBy, currentCopy(filed, template));
        return Objects.requireNonNull(liveFor(event.id(), date, memberId, template.id()), "the agreement was asked");
    }

    private @Nullable AppointmentRequest liveFor(int eventId, LocalDate date, int memberId, int templateId) {
        return requests.liveForAppointment(eventId, date, memberId).stream()
                .filter(found -> found.templateId() == templateId)
                .reduce((first, second) -> second)
                .orElse(null);
    }

    /**
     * Whether the member said they will not come on a date of an appointment that takes no registrations.
     * A refusal they took back again is no refusal.
     */
    private boolean refused(int eventId, LocalDate date, int memberId) {
        return registrations.findByEventAndDate(eventId, date).stream()
                .anyMatch(registration ->
                        registration.memberId() == memberId && registration.status() == RegistrationStatus.DECLINED);
    }

    /** The member's registration for the date where it holds a place, pending or accepted, else null. */
    private @Nullable EventRegistration placeOf(int eventId, LocalDate date, int memberId) {
        if (!registrations.findRegisteredMemberIds(eventId, date).contains(memberId)) return null;
        return registrations.findByEventAndDate(eventId, date).stream()
                .filter(registration -> registration.memberId() == memberId)
                .findFirst()
                .orElse(null);
    }

    /** The documents nothing is asked for again: signatures already asked for, or the paper copy confirmed. */
    private Set<Integer> settledTemplates(int eventId, LocalDate date, int memberId) {
        var settled = requests.liveForAppointment(eventId, date, memberId).stream()
                .map(AppointmentRequest::templateId)
                .collect(Collectors.toCollection(HashSet::new));
        scans.latest(eventId, date, List.of(memberId)).stream()
                .filter(scan -> scan.state() == PaperState.CONFIRMED)
                .map(PaperSubmission::templateId)
                .forEach(settled::add);
        return settled;
    }

    /**
     * The copy filed for the template that can be asked on, if any: one of the template's current version,
     * and not one left unsigned by an issuer who would sign it now.
     */
    private @Nullable RequirementGeneration currentCopy(List<RequirementGeneration> filed, DocumentTemplate template) {
        return filed.stream()
                .filter(copy -> copy.templateId() == template.id() && copy.templateVersion() >= template.version())
                .filter(copy -> !issuerWouldSignNow(copy))
                .findFirst()
                .orElse(null);
    }

    /**
     * Whether a copy was filed without its issuer's signature although its issuer would sign it now, as one
     * fetched before the issuer agreed to letters being signed for them. Such a copy is generated again,
     * which signs it for the issuer, so the document completes without anyone acting for the station.
     */
    private boolean issuerWouldSignNow(RequirementGeneration copy) {
        var generation = generations.findById(copy.generationId()).orElse(null);
        if (generation == null || !generation.issuerSigns() || !generation.issuerFixed()) return false;
        Integer issuerId = generation.issuerId();
        return issuerId != null
                && issuerSignatures.findByGeneration(copy.generationId()).isEmpty()
                && letterSigner.signsFor(issuerId);
    }

    /**
     * Asks on the current copy where one is filed and still asks for signatures as it was generated, else on
     * a copy generated now.
     */
    private void ask(
            StationEvent event,
            LocalDate date,
            DocumentTemplate template,
            int memberId,
            int generatedBy,
            @Nullable RequirementGeneration copy) {
        if (copy != null) {
            try {
                requestService.requestForAppointment(copy.generationId());
                return;
            } catch (RefusalResponse e) {
                log.info(
                        "Copy {} of template {} cannot be asked on ({}), generating a new one",
                        copy.documentId(),
                        template.id(),
                        e.refusal());
            }
        }
        var generated = appointments.generateFor(event, date, template, memberId, generatedBy);
        requestService.requestForAppointment(generated.generationId());
    }
}
