/*
 *     SPDX-License-Identifier: AGPL-3.0-only
 *
 *     Copyright (C) RainbowDashLabs and Contributor
 */
package dev.chojo.ember.feature.generator.service;

import dev.chojo.ember.feature.generator.entity.GenerationLogEntry;
import dev.chojo.ember.feature.generator.repository.DocumentGenerationRepository;
import dev.chojo.ember.feature.members.service.MemberNameResolver;
import dev.chojo.ember.feature.signing.entity.SignatureSummary;
import dev.chojo.ember.feature.signing.service.SignatureSummaries;
import jakarta.inject.Inject;
import jakarta.inject.Singleton;
import org.jspecify.annotations.Nullable;

import java.time.Instant;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.stream.Collectors;
import java.util.stream.Stream;

/**
 * The documents a station generated from templates, as a list: who has which document, from which
 * template and which version of it, generated by whom and when, who issued it, and how the signatures
 * asked for on it stand.
 */
@Singleton
public class GenerationLogService {
    /** How many entries a page holds where the reader asks for no number. */
    public static final int DEFAULT_LIMIT = 500;

    /** The most entries one page holds. */
    public static final int MAX_LIMIT = 1000;

    private final DocumentGenerationRepository generations;
    private final MemberNameResolver names;
    private final SignatureSummaries signatures;

    @Inject
    public GenerationLogService(
            DocumentGenerationRepository generations, MemberNameResolver names, SignatureSummaries signatures) {
        this.generations = generations;
        this.names = names;
        this.signatures = signatures;
    }

    /**
     * One generated document as the list shows it.
     *
     * @param id              the entry of the generation log
     * @param generatedAt     when it was generated
     * @param templateId      the template it came from
     * @param templateName    what the template is called now
     * @param templateVersion the version of the template at the time
     * @param ofAssociation   whether the template is one of the station's association
     * @param memberId        the member it is about, or null once they were deleted
     * @param memberName      the member's name, or null once they were deleted
     * @param generatedByName who generated it, or null once they are gone
     * @param selfService     whether it was generated through self service
     * @param documentId      the member document it was filed as, or null once that was deleted
     * @param issuerName      who issued it, or null where it names nobody or they are gone
     * @param issuerFunction  what the issuer does at the station, as printed, or null
     * @param signature       how the signatures asked for on it stand, or null where nobody was asked to sign it
     */
    public record GeneratedDocumentEntry(
            int id,
            Instant generatedAt,
            int templateId,
            String templateName,
            int templateVersion,
            boolean ofAssociation,
            @Nullable Integer memberId,
            @Nullable String memberName,
            @Nullable String generatedByName,
            boolean selfService,
            @Nullable Integer documentId,
            @Nullable String issuerName,
            @Nullable String issuerFunction,
            @Nullable SignatureSummary signature) {}

    /**
     * One page of the documents generated at a station. The names of everybody the page names are read
     * together rather than row by row.
     *
     * @param stationId the station
     * @param limit     how many entries at most, held between 1 and {@value #MAX_LIMIT}
     * @param offset    how many of the newest entries to pass over, none where it is below zero
     * @return the documents generated at the station, the newest first
     */
    public List<GeneratedDocumentEntry> list(int stationId, int limit, int offset) {
        var entries = generations.forStation(stationId, Math.clamp(limit, 1, MAX_LIMIT), Math.max(offset, 0));
        var named = names.identified(entries.stream()
                .flatMap(entry -> Stream.of(entry.memberId(), entry.generatedBy(), entry.issuerId()))
                .filter(Objects::nonNull)
                .collect(Collectors.toSet()));
        var signed = signatures.ofGenerations(
                entries.stream().map(GenerationLogEntry::id).toList());
        return entries.stream()
                .map(entry -> entry(entry, named, signed.get(entry.id())))
                .toList();
    }

    private static GeneratedDocumentEntry entry(
            GenerationLogEntry entry, Map<Integer, String> named, @Nullable SignatureSummary signature) {
        return new GeneratedDocumentEntry(
                entry.id(),
                entry.generatedAt(),
                entry.templateId(),
                entry.templateName(),
                entry.templateVersion(),
                entry.ofAssociation(),
                entry.memberId(),
                nameOf(entry.memberId(), named),
                nameOf(entry.generatedBy(), named),
                entry.selfService(),
                entry.documentId(),
                nameOf(entry.issuerId(), named),
                entry.issuerFunction(),
                signature);
    }

    private static @Nullable String nameOf(@Nullable Integer memberId, Map<Integer, String> named) {
        return memberId == null ? null : named.get(memberId);
    }
}
