/*
 *     SPDX-License-Identifier: AGPL-3.0-only
 *
 *     Copyright (C) RainbowDashLabs and Contributor
 */
package dev.chojo.ember.feature.generator.service;

import dev.chojo.ember.feature.generator.entity.GenerationLogEntry;
import dev.chojo.ember.feature.generator.repository.DocumentGenerationRepository;
import dev.chojo.ember.feature.members.service.MemberNameResolver;
import jakarta.inject.Inject;
import jakarta.inject.Singleton;
import org.jspecify.annotations.Nullable;

import java.time.Instant;
import java.util.List;

/**
 * The documents a station generated from templates, as a list: who has which document, from which
 * template and which version of it, generated by whom and when.
 */
@Singleton
public class GenerationLogService {
    private final DocumentGenerationRepository generations;
    private final MemberNameResolver names;

    @Inject
    public GenerationLogService(DocumentGenerationRepository generations, MemberNameResolver names) {
        this.generations = generations;
        this.names = names;
    }

    /**
     * One generated document as the list shows it.
     *
     * @param id              the entry of the generation log
     * @param generatedAt     when it was generated
     * @param templateId      the template it came from
     * @param templateName    what the template is called now
     * @param templateVersion the version of the template at the time
     * @param ofAssociation   whether the template is one of the station's association
     * @param memberId        the member it is about, or null once they were deleted
     * @param memberName      the member's name, or null once they were deleted
     * @param generatedByName who generated it, or null once they are gone
     * @param selfService     whether it was generated through self service
     * @param documentId      the member document it was filed as, or null once that was deleted
     */
    public record GeneratedDocumentEntry(
            int id,
            Instant generatedAt,
            int templateId,
            String templateName,
            int templateVersion,
            boolean ofAssociation,
            @Nullable Integer memberId,
            @Nullable String memberName,
            @Nullable String generatedByName,
            boolean selfService,
            @Nullable Integer documentId) {}

    /**
     * @param stationId the station
     * @return every document generated at the station, the newest first
     */
    public List<GeneratedDocumentEntry> list(int stationId) {
        return generations.forStation(stationId).stream().map(this::entry).toList();
    }

    private GeneratedDocumentEntry entry(GenerationLogEntry entry) {
        return new GeneratedDocumentEntry(
                entry.id(),
                entry.generatedAt(),
                entry.templateId(),
                entry.templateName(),
                entry.templateVersion(),
                entry.ofAssociation(),
                entry.memberId(),
                nameOf(entry.memberId()),
                nameOf(entry.generatedBy()),
                entry.selfService(),
                entry.documentId());
    }

    private @Nullable String nameOf(@Nullable Integer memberId) {
        return memberId == null ? null : names.identified(memberId);
    }
}
