/*
 *     SPDX-License-Identifier: AGPL-3.0-only
 *
 *     Copyright (C) RainbowDashLabs and Contributor
 */
package dev.chojo.ember.feature.generator.entity;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.Optional;

/**
 * The placeholders every station has, whatever questions it asks.
 *
 * <p>The profile questions add theirs on top as {@code profile.<id>}, and the guardians' answers to them
 * as {@code guardian1.profile.<id>} and {@code guardian2.profile.<id>}; an association's questions the same
 * way with {@code associationProfile.<id>}. The pronouns for the member are {@link PronounKey}s.
 *
 * <p>Names are official names throughout: the register's first name and surname, never the name a
 * member is called by. {@link #MEMBER_CALLED_NAME} is the one exception and is kept out of legal
 * templates.
 *
 * <p>The values of a person stand in the picker below the {@link PlaceholderSubgroup#DETAILS details}
 * of the member or the guardian, the others right below their category. A guardian's value is named
 * shortly there, and its label puts the guardian in front; so does the label of a value of the issuer
 * ({@link DocumentIssuer}), "Ausstellende Person: Name".
 */
public enum BuiltInPlaceholder {
    MEMBER_FIRST_NAME("member.firstName", PlaceholderCategory.MEMBER, "Vorname", "First name"),
    MEMBER_LAST_NAME("member.lastName", PlaceholderCategory.MEMBER, "Nachname", "Last name"),
    MEMBER_FULL_NAME("member.fullName", PlaceholderCategory.MEMBER, "Vor- und Nachname", "Full name"),
    MEMBER_CALLED_NAME("member.calledName", PlaceholderCategory.MEMBER, "Rufname", "Called name"),
    MEMBER_BIRTH_DATE("member.birthDate", PlaceholderCategory.MEMBER, "Geburtsdatum", "Date of birth"),
    MEMBER_AGE("member.age", PlaceholderCategory.MEMBER, "Alter", "Age"),
    MEMBER_JOIN_DATE("member.joinDate", PlaceholderCategory.MEMBER, "Mitglied seit", "Member since"),
    MEMBER_JOIN_MONTH(
            "member.joinDate.monthYear",
            PlaceholderCategory.MEMBER,
            "Mitglied seit (Monat und Jahr)",
            "Member since (month and year)"),
    MEMBER_USER_TYPE("member.userType", PlaceholderCategory.MEMBER, "Mitgliedsart", "Member type"),
    GUARDIAN1_FULL_NAME("guardian1.fullName", PlaceholderCategory.GUARDIAN1, "Name", "Name"),
    GUARDIAN1_FIRST_NAME("guardian1.firstName", PlaceholderCategory.GUARDIAN1, "Vorname", "First name"),
    GUARDIAN1_LAST_NAME("guardian1.lastName", PlaceholderCategory.GUARDIAN1, "Nachname", "Last name"),
    GUARDIAN2_FULL_NAME("guardian2.fullName", PlaceholderCategory.GUARDIAN2, "Name", "Name"),
    GUARDIAN2_FIRST_NAME("guardian2.firstName", PlaceholderCategory.GUARDIAN2, "Vorname", "First name"),
    GUARDIAN2_LAST_NAME("guardian2.lastName", PlaceholderCategory.GUARDIAN2, "Nachname", "Last name"),
    STATION_NAME("station.name", PlaceholderCategory.STATION, "Name der Wache", "Station name"),
    STATION_ADDRESS("station.address", PlaceholderCategory.STATION, "Straße der Wache", "Station street"),
    STATION_POSTAL_CODE(
            "station.postalCode", PlaceholderCategory.STATION, "Postleitzahl der Wache", "Station postal code"),
    STATION_CITY("station.city", PlaceholderCategory.STATION, "Ort der Wache", "Station city"),
    ASSOCIATION_NAME("association.name", PlaceholderCategory.ASSOCIATION, "Name des Verbands", "Association name"),
    ASSOCIATION_ADDRESS(
            "association.address", PlaceholderCategory.ASSOCIATION, "Anschrift des Verbands", "Association address"),
    EVENT_NAME("event.name", PlaceholderCategory.APPOINTMENT, "Termin", "Appointment"),
    EVENT_START("event.start", PlaceholderCategory.APPOINTMENT, "Beginn des Termins", "Appointment start"),
    EVENT_END("event.end", PlaceholderCategory.APPOINTMENT, "Ende des Termins", "Appointment end"),
    EVENT_LOCATION("event.location", PlaceholderCategory.APPOINTMENT, "Ort des Termins", "Appointment location"),
    ISSUER_FULL_NAME("issuer.fullName", PlaceholderCategory.ISSUER, "Name", "Name"),
    ISSUER_FUNCTION("issuer.function", PlaceholderCategory.ISSUER, "Funktion", "Function"),
    TODAY("today", PlaceholderCategory.DOCUMENT, "Heutiges Datum", "Today's date"),
    TODAY_LONG(
            "today.long", PlaceholderCategory.DOCUMENT, "Heutiges Datum, ausgeschrieben", "Today's date, written out"),
    GENERATED_BY("generatedBy.fullName", PlaceholderCategory.DOCUMENT, "Erstellt von", "Generated by");

    private final String key;
    private final PlaceholderCategory category;
    private final String german;
    private final String english;

    BuiltInPlaceholder(String key, PlaceholderCategory category, String german, String english) {
        this.key = key;
        this.category = category;
        this.german = german;
        this.english = english;
    }

    /** @return the key a template writes */
    public String key() {
        return key;
    }

    /**
     * @param language {@code de} or {@code en}
     * @return the placeholder as the catalogue offers it in that language
     */
    public Placeholder in(String language) {
        String name = "en".equals(language) ? english : german;
        String categoryWord = category.word(language);
        var group = category.group();
        boolean guardian = group == PlaceholderGroup.GUARDIAN;
        var path = guardian || group == PlaceholderGroup.MEMBER
                ? List.of(categoryWord, PlaceholderSubgroup.DETAILS.word(language), name)
                : List.of(categoryWord, name);
        boolean namedByWhose = guardian || group == PlaceholderGroup.ISSUER;
        return new Placeholder(
                key,
                namedByWhose ? categoryWord + ": " + name : name,
                group,
                category,
                path,
                this == MEMBER_CALLED_NAME,
                group == PlaceholderGroup.EVENT);
    }

    /**
     * @param key a key a template wrote
     * @return the built-in placeholder of that key, or empty where it is none
     */
    public static Optional<BuiltInPlaceholder> of(String key) {
        return Arrays.stream(values()).filter(value -> value.key.equals(key)).findFirst();
    }

    /**
     * @param keys the keys a document names
     * @return whether one of them is a value of the issuer
     */
    public static boolean namesIssuer(Collection<String> keys) {
        return keys.stream()
                .map(BuiltInPlaceholder::of)
                .flatMap(Optional::stream)
                .anyMatch(placeholder -> placeholder.category == PlaceholderCategory.ISSUER);
    }
}
