/*
 *     SPDX-License-Identifier: AGPL-3.0-only
 *
 *     Copyright (C) RainbowDashLabs and Contributor
 */
package dev.chojo.ember.feature.generator.entity;

import org.jspecify.annotations.Nullable;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.Optional;

/**
 * The placeholders every station has, whatever questions it asks.
 *
 * <p>The profile questions add theirs on top as {@code profile.<id>}, and the guardians' answers to them
 * as {@code guardian1.profile.<id>} and {@code guardian2.profile.<id>}; an association's questions the same
 * way with {@code associationProfile.<id>}. The pronouns for the member are {@link PronounKey}s.
 *
 * <p>Names are official names throughout: the register's first name and surname, never the name a
 * member is called by. {@link #MEMBER_CALLED_NAME} is the one exception and is kept out of legal
 * templates.
 *
 * <p>The values of a person stand in the picker below the {@link PlaceholderSubgroup#DETAILS details}
 * of the member or the guardian, the others right below their category. A guardian's value is named
 * shortly there, and its label puts the guardian in front; so does the label of a value of the issuer
 * ({@link DocumentIssuer}), "Ausstellende Person: Name".
 *
 * <p>A value that holds a date has one key, whatever it prints like: the format is written after a bar
 * ({@link PlaceholderKey}), so the join date as month and year is {@code member.joinDate|monthYear}.
 */
public enum BuiltInPlaceholder {
    MEMBER_FIRST_NAME("member.firstName", PlaceholderCategory.MEMBER, "Vorname", "First name"),
    MEMBER_LAST_NAME("member.lastName", PlaceholderCategory.MEMBER, "Nachname", "Last name"),
    MEMBER_FULL_NAME("member.fullName", PlaceholderCategory.MEMBER, "Vor- und Nachname", "Full name"),
    MEMBER_CALLED_NAME("member.calledName", PlaceholderCategory.MEMBER, "Rufname", "Called name"),
    MEMBER_BIRTH_DATE("member.birthDate", PlaceholderCategory.MEMBER, "Geburtsdatum", "Date of birth"),
    MEMBER_AGE("member.age", PlaceholderCategory.MEMBER, "Alter", "Age"),
    MEMBER_JOIN_DATE("member.joinDate", PlaceholderCategory.MEMBER, "Mitglied seit", "Member since"),
    MEMBER_USER_TYPE("member.userType", PlaceholderCategory.MEMBER, "Mitgliedsart", "Member type"),
    GUARDIAN1_FULL_NAME("guardian1.fullName", PlaceholderCategory.GUARDIAN1, "Name", "Name"),
    GUARDIAN1_FIRST_NAME("guardian1.firstName", PlaceholderCategory.GUARDIAN1, "Vorname", "First name"),
    GUARDIAN1_LAST_NAME("guardian1.lastName", PlaceholderCategory.GUARDIAN1, "Nachname", "Last name"),
    GUARDIAN2_FULL_NAME("guardian2.fullName", PlaceholderCategory.GUARDIAN2, "Name", "Name"),
    GUARDIAN2_FIRST_NAME("guardian2.firstName", PlaceholderCategory.GUARDIAN2, "Vorname", "First name"),
    GUARDIAN2_LAST_NAME("guardian2.lastName", PlaceholderCategory.GUARDIAN2, "Nachname", "Last name"),
    STATION_NAME("station.name", PlaceholderCategory.STATION, "Name der Wache", "Station name"),
    STATION_ADDRESS("station.address", PlaceholderCategory.STATION, "Straße der Wache", "Station street"),
    STATION_POSTAL_CODE(
            "station.postalCode", PlaceholderCategory.STATION, "Postleitzahl der Wache", "Station postal code"),
    STATION_CITY("station.city", PlaceholderCategory.STATION, "Ort der Wache", "Station city"),
    ASSOCIATION_NAME("association.name", PlaceholderCategory.ASSOCIATION, "Name des Verbands", "Association name"),
    ASSOCIATION_ADDRESS(
            "association.address", PlaceholderCategory.ASSOCIATION, "Anschrift des Verbands", "Association address"),
    EVENT_NAME("event.name", PlaceholderCategory.APPOINTMENT, "Termin", "Appointment"),
    EVENT_START("event.start", PlaceholderCategory.APPOINTMENT, "Beginn des Termins", "Appointment start"),
    EVENT_END("event.end", PlaceholderCategory.APPOINTMENT, "Ende des Termins", "Appointment end"),
    EVENT_LOCATION("event.location", PlaceholderCategory.APPOINTMENT, "Ort des Termins", "Appointment location"),
    ISSUER_FULL_NAME("issuer.fullName", PlaceholderCategory.ISSUER, "Name", "Name"),
    ISSUER_FUNCTION("issuer.function", PlaceholderCategory.ISSUER, "Funktion", "Function"),
    TODAY("today", PlaceholderCategory.DOCUMENT, "Heutiges Datum", "Today's date"),
    GENERATED_BY("generatedBy.fullName", PlaceholderCategory.DOCUMENT, "Erstellt von", "Generated by");

    private final String key;
    private final PlaceholderCategory category;
    private final String german;
    private final String english;

    BuiltInPlaceholder(String key, PlaceholderCategory category, String german, String english) {
        this.key = key;
        this.category = category;
        this.german = german;
        this.english = english;
    }

    /** @return the key a template writes */
    public String key() {
        return key;
    }

    /**
     * @return whether its value is known without a member: today's date, and the data of the station and
     *         of its association
     */
    public boolean needsNoMember() {
        return this == TODAY || category == PlaceholderCategory.STATION || category == PlaceholderCategory.ASSOCIATION;
    }

    /** @return what kind of date it holds, or null where it holds none */
    public @Nullable DateKind dateKind() {
        return switch (this) {
            case MEMBER_BIRTH_DATE, MEMBER_JOIN_DATE, TODAY -> DateKind.DATE;
            case EVENT_START, EVENT_END -> DateKind.DATE_TIME;
            default -> null;
        };
    }

    /**
     * @param language the language the picker speaks
     * @return the placeholder as the catalogue offers it in that language
     */
    public Placeholder in(DocumentLanguage language) {
        String name = language.pick(german, english);
        String categoryWord = category.word(language);
        boolean guardian = category.guardian();
        var path = guardian || category == PlaceholderCategory.MEMBER
                ? List.of(categoryWord, PlaceholderSubgroup.DETAILS.word(language), name)
                : List.of(categoryWord, name);
        boolean namedByWhose = guardian || category == PlaceholderCategory.ISSUER;
        return new Placeholder(
                key,
                namedByWhose ? categoryWord + ": " + name : name,
                category,
                path,
                this == MEMBER_CALLED_NAME,
                category == PlaceholderCategory.APPOINTMENT,
                dateKind());
    }

    /**
     * @param key a key a template wrote, with or without a format
     * @return the built-in placeholder of that key, or empty where it is none
     */
    public static Optional<BuiltInPlaceholder> of(String key) {
        String base = PlaceholderKey.parse(key).base();
        return Arrays.stream(values()).filter(value -> value.key.equals(base)).findFirst();
    }

    /**
     * @param keys the keys a document names
     * @return whether one of them is a value of the issuer
     */
    public static boolean namesIssuer(Collection<String> keys) {
        return keys.stream()
                .map(BuiltInPlaceholder::of)
                .flatMap(Optional::stream)
                .anyMatch(placeholder -> placeholder.category == PlaceholderCategory.ISSUER);
    }
}
