/*
 *     SPDX-License-Identifier: AGPL-3.0-only
 *
 *     Copyright (C) RainbowDashLabs and Contributor
 */
package dev.chojo.ember.feature.generator.entity;

import java.util.Arrays;
import java.util.Optional;

/**
 * The placeholders every station has, whatever questions it asks.
 *
 * <p>The profile questions add theirs on top as {@code profile.<id>}, and the guardians' answers to them
 * as {@code guardian1.profile.<id>} and {@code guardian2.profile.<id>}.
 *
 * <p>Names are official names throughout: the register's first name and surname, never the name a
 * member is called by. {@link #MEMBER_CALLED_NAME} is the one exception and is kept out of legal
 * templates.
 */
public enum BuiltInPlaceholder {
    MEMBER_FIRST_NAME("member.firstName", PlaceholderGroup.MEMBER, "Vorname", "First name"),
    MEMBER_LAST_NAME("member.lastName", PlaceholderGroup.MEMBER, "Nachname", "Last name"),
    MEMBER_FULL_NAME("member.fullName", PlaceholderGroup.MEMBER, "Vor- und Nachname", "Full name"),
    MEMBER_CALLED_NAME("member.calledName", PlaceholderGroup.MEMBER, "Rufname", "Called name"),
    MEMBER_BIRTH_DATE("member.birthDate", PlaceholderGroup.MEMBER, "Geburtsdatum", "Date of birth"),
    MEMBER_AGE("member.age", PlaceholderGroup.MEMBER, "Alter", "Age"),
    MEMBER_JOIN_DATE("member.joinDate", PlaceholderGroup.MEMBER, "Mitglied seit", "Member since"),
    MEMBER_JOIN_MONTH(
            "member.joinDate.monthYear",
            PlaceholderGroup.MEMBER,
            "Mitglied seit (Monat und Jahr)",
            "Member since (month and year)"),
    MEMBER_USER_TYPE("member.userType", PlaceholderGroup.MEMBER, "Mitgliedsart", "Member type"),
    GUARDIAN1_FULL_NAME(
            "guardian1.fullName", PlaceholderGroup.GUARDIAN, "Erziehungsberechtigte 1: Name", "Guardian 1: name"),
    GUARDIAN1_FIRST_NAME(
            "guardian1.firstName",
            PlaceholderGroup.GUARDIAN,
            "Erziehungsberechtigte 1: Vorname",
            "Guardian 1: first name"),
    GUARDIAN1_LAST_NAME(
            "guardian1.lastName",
            PlaceholderGroup.GUARDIAN,
            "Erziehungsberechtigte 1: Nachname",
            "Guardian 1: last name"),
    GUARDIAN2_FULL_NAME(
            "guardian2.fullName", PlaceholderGroup.GUARDIAN, "Erziehungsberechtigte 2: Name", "Guardian 2: name"),
    GUARDIAN2_FIRST_NAME(
            "guardian2.firstName",
            PlaceholderGroup.GUARDIAN,
            "Erziehungsberechtigte 2: Vorname",
            "Guardian 2: first name"),
    GUARDIAN2_LAST_NAME(
            "guardian2.lastName",
            PlaceholderGroup.GUARDIAN,
            "Erziehungsberechtigte 2: Nachname",
            "Guardian 2: last name"),
    STATION_NAME("station.name", PlaceholderGroup.STATION, "Name der Wache", "Station name"),
    STATION_ADDRESS("station.address", PlaceholderGroup.STATION, "Straße der Wache", "Station street"),
    STATION_POSTAL_CODE(
            "station.postalCode", PlaceholderGroup.STATION, "Postleitzahl der Wache", "Station postal code"),
    STATION_CITY("station.city", PlaceholderGroup.STATION, "Ort der Wache", "Station city"),
    EVENT_NAME("event.name", PlaceholderGroup.EVENT, "Termin", "Appointment"),
    EVENT_START("event.start", PlaceholderGroup.EVENT, "Beginn des Termins", "Appointment start"),
    EVENT_END("event.end", PlaceholderGroup.EVENT, "Ende des Termins", "Appointment end"),
    EVENT_LOCATION("event.location", PlaceholderGroup.EVENT, "Ort des Termins", "Appointment location"),
    TODAY("today", PlaceholderGroup.DOCUMENT, "Heutiges Datum", "Today's date"),
    TODAY_LONG("today.long", PlaceholderGroup.DOCUMENT, "Heutiges Datum, ausgeschrieben", "Today's date, written out"),
    GENERATED_BY("generatedBy.fullName", PlaceholderGroup.DOCUMENT, "Erstellt von", "Generated by"),
    PRONOUN_SUBJECT("pronoun.subject", PlaceholderGroup.PRONOUN, "er / sie / Name", "he / she / name"),
    PRONOUN_OBJECT("pronoun.object", PlaceholderGroup.PRONOUN, "ihn / sie / Name", "him / her / name"),
    PRONOUN_DATIVE("pronoun.dative", PlaceholderGroup.PRONOUN, "ihm / ihr / Name", "him / her / name"),
    PRONOUN_POSSESSIVE("pronoun.possessive", PlaceholderGroup.PRONOUN, "sein / ihr / Namens", "his / her / name's"),
    PRONOUN_SUBJECT_START(
            "pronoun.subject.start", PlaceholderGroup.PRONOUN, "Er / Sie / Name (Satzanfang)", "He / She / name"),
    PRONOUN_OBJECT_START(
            "pronoun.object.start", PlaceholderGroup.PRONOUN, "Ihn / Sie / Name (Satzanfang)", "Him / Her / name"),
    PRONOUN_DATIVE_START(
            "pronoun.dative.start", PlaceholderGroup.PRONOUN, "Ihm / Ihr / Name (Satzanfang)", "Him / Her / name"),
    PRONOUN_POSSESSIVE_START(
            "pronoun.possessive.start",
            PlaceholderGroup.PRONOUN,
            "Sein / Ihr / Namens (Satzanfang)",
            "His / Her / name's");

    private final String key;
    private final PlaceholderGroup group;
    private final String german;
    private final String english;

    BuiltInPlaceholder(String key, PlaceholderGroup group, String german, String english) {
        this.key = key;
        this.group = group;
        this.german = german;
        this.english = english;
    }

    /** @return the key a template writes */
    public String key() {
        return key;
    }

    /**
     * @param language {@code de} or {@code en}
     * @return the placeholder as the catalogue offers it in that language
     */
    public Placeholder in(String language) {
        return new Placeholder(
                key,
                "en".equals(language) ? english : german,
                group,
                this == MEMBER_CALLED_NAME,
                group == PlaceholderGroup.EVENT);
    }

    /**
     * @param key a key a template wrote
     * @return the built-in placeholder of that key, or empty where it is none
     */
    public static Optional<BuiltInPlaceholder> of(String key) {
        return Arrays.stream(values()).filter(value -> value.key.equals(key)).findFirst();
    }
}
