/*
 *     SPDX-License-Identifier: AGPL-3.0-only
 *
 *     Copyright (C) RainbowDashLabs and Contributor
 */
package dev.chojo.ember.feature.generator.entity;

import org.jspecify.annotations.Nullable;

import java.time.LocalDate;

/**
 * How a document came to be generated, which decides whether the member it is about sees it and what
 * the generation log says about it.
 *
 * @param way       who generated it in which role
 * @param eventId   the appointment that asks for it, or null where none does
 * @param eventDate the date of that appointment the document is for, or null where none does
 */
public record GenerationOrigin(
        GenerationWay way,
        @Nullable Integer eventId,
        @Nullable LocalDate eventDate) {

    /** Generated by a manager. */
    public static final GenerationOrigin MANAGER = new GenerationOrigin(GenerationWay.MANAGER, null, null);

    /** Generated by the member or their guardian through self service. */
    public static final GenerationOrigin SELF_SERVICE = new GenerationOrigin(GenerationWay.SELF_SERVICE, null, null);

    /**
     * Generated by a participant or their guardian because an appointment asks for it.
     *
     * @param eventId   the appointment
     * @param eventDate the date of the appointment
     * @return the origin
     */
    public static GenerationOrigin appointment(int eventId, LocalDate eventDate) {
        return new GenerationOrigin(GenerationWay.APPOINTMENT, eventId, eventDate);
    }

    /** @return whether the member or their guardian generated it for themselves, which the cooldown counts */
    public boolean selfService() {
        return way == GenerationWay.SELF_SERVICE;
    }

    /** @return whether a manager generated it, who may hide it from the member as the template says */
    public boolean byManager() {
        return way == GenerationWay.MANAGER;
    }
}
