/*
 *     SPDX-License-Identifier: AGPL-3.0-only
 *
 *     Copyright (C) RainbowDashLabs and Contributor
 */
package dev.chojo.ember.feature.generator.entity;

import org.jspecify.annotations.Nullable;

import java.time.Instant;

/**
 * What a document is generated in the light of, beyond the member it is about.
 *
 * @param generatedBy the member who generates it, or null where nobody does, as for a preview
 * @param event       the appointment it is generated for, or null where it is generated on its own
 * @param issuer      who issues it for the station
 */
public record GenerationContext(
        @Nullable Integer generatedBy, @Nullable EventFacts event, DocumentIssuer issuer) {

    /** A document nobody generates, for no appointment and without an issuer, as a preview without a member. */
    public static final GenerationContext NOBODY = new GenerationContext(null, null, DocumentIssuer.NONE);

    /**
     * A document generated by a member, for no appointment.
     *
     * @param memberId the member who generates it
     * @param issuer   who issues it
     * @return the context
     */
    public static GenerationContext by(int memberId, DocumentIssuer issuer) {
        return new GenerationContext(memberId, null, issuer);
    }

    /**
     * What a document says about the appointment it is generated for.
     *
     * @param name     what the appointment is called
     * @param start    when it begins
     * @param end      when it ends
     * @param location where it takes place, or null where that is not said
     */
    public record EventFacts(
            String name,
            Instant start,
            Instant end,
            @Nullable String location) {}
}
