/*
 *     SPDX-License-Identifier: AGPL-3.0-only
 *
 *     Copyright (C) RainbowDashLabs and Contributor
 */
import type {
    StationModule,
    StationPermission as StationPermissionUnion,
    StationUserType as StationUserTypeUnion,
} from './generated/schema'

export const StationUserType = {
    TRIAL: 'TRIAL',
    MEMBER: 'MEMBER',
    GUARDIAN: 'GUARDIAN',
    TEAM: 'TEAM',
    MANAGER: 'MANAGER',
} as const satisfies Record<StationUserTypeUnion, StationUserTypeUnion>

/**
 * Human-readable German labels for each station user type. Single source of truth
 * for any picker, badge, filter, or summary that needs to render a user type name
 * without going through i18n.
 */
export const StationUserTypeLabels: Record<StationUserTypeUnion, string> = {
    TRIAL: 'Probe',
    MEMBER: 'Mitglied',
    GUARDIAN: 'Erziehungsberechtigter',
    TEAM: 'Team',
    MANAGER: 'Manager',
}

export const StationPermission = {
    LOGIN: 'LOGIN',
    USER: 'USER',
    ATTENDANCE_READ: 'ATTENDANCE_READ',
    ATTENDANCE_EDIT: 'ATTENDANCE_EDIT',
    ATTENDANCE_CONFIGURE: 'ATTENDANCE_CONFIGURE',
    ATTENDANCE_EXPORT: 'ATTENDANCE_EXPORT',
    ATTENDANCE_MANAGER: 'ATTENDANCE_MANAGER',
    INVENTORY_CREATE_EXTERNAL: 'INVENTORY_CREATE_EXTERNAL',
    INVENTORY_CREATE_INTERNAL: 'INVENTORY_CREATE_INTERNAL',
    INVENTORY_CREATE: 'INVENTORY_CREATE',
    INVENTORY_READ: 'INVENTORY_READ',
    INVENTORY_EDIT: 'INVENTORY_EDIT',
    INVENTORY_PROCUREMENT: 'INVENTORY_PROCUREMENT',
    INVENTORY_MOVEMENTS: 'INVENTORY_MOVEMENTS',
    INVENTORY_CHECK: 'INVENTORY_CHECK',
    INVENTORY_LENDING_REQUEST: 'INVENTORY_LENDING_REQUEST',
    INVENTORY_LENDING_MANAGER: 'INVENTORY_LENDING_MANAGER',
    INVENTORY_ASSIGN: 'INVENTORY_ASSIGN',
    INVENTORY_STORAGE: 'INVENTORY_STORAGE',
    INVENTORY_MANAGER: 'INVENTORY_MANAGER',
    EVENT_MANAGE_TEMPLATE: 'EVENT_MANAGE_TEMPLATE',
    EVENT_MANAGE_CATEGORY: 'EVENT_MANAGE_CATEGORY',
    EVENT_EDIT: 'EVENT_EDIT',
    EVENT_INTERNAL: 'EVENT_INTERNAL',
    EVENT_REGISTRATION: 'EVENT_REGISTRATION',
    EVENTS_FEDERATE: 'EVENTS_FEDERATE',
    EVENT_MANAGER: 'EVENT_MANAGER',
    DOCUMENT_READ: 'DOCUMENT_READ',
    DOCUMENT_READ_MEMBER: 'DOCUMENT_READ_MEMBER',
    DOCUMENT_EDIT: 'DOCUMENT_EDIT',
    DOCUMENT_EDIT_MEMBER: 'DOCUMENT_EDIT_MEMBER',
    DOCUMENT_MANAGER: 'DOCUMENT_MANAGER',
    MEMBER_READ: 'MEMBER_READ',
    MEMBER_NOTES: 'MEMBER_NOTES',
    MEMBER_GUARDIAN: 'MEMBER_GUARDIAN',
    MEMBER_CHANGES: 'MEMBER_CHANGES',
    MEMBER_MANAGE_GROUP: 'MEMBER_MANAGE_GROUP',
    MEMBER_MANAGE_TAGS: 'MEMBER_MANAGE_TAGS',
    MEMBER_SELF_UPLOAD: 'MEMBER_SELF_UPLOAD',
    MEMBER_EDIT: 'MEMBER_EDIT',
    MEMBER_FIELDS: 'MEMBER_FIELDS',
    MEMBER_EXPORT: 'MEMBER_EXPORT',
    MEMBER_MANAGER: 'MEMBER_MANAGER',
    WAITLIST_READ: 'WAITLIST_READ',
    WAITLIST_ADD: 'WAITLIST_ADD',
    WAITLIST_EDIT: 'WAITLIST_EDIT',
    WAITLIST_MANAGER: 'WAITLIST_MANAGER',
    NEWS_EDIT: 'NEWS_EDIT',
    NEWS_FEDERATE: 'NEWS_FEDERATE',
    NEWS_MANAGER: 'NEWS_MANAGER',
    POLL_VIEW_RESULTS: 'POLL_VIEW_RESULTS',
    POLL_CREATE: 'POLL_CREATE',
    POLL_MANAGER: 'POLL_MANAGER',
    LOST_AND_FOUND_CREATE: 'LOST_AND_FOUND_CREATE',
    LOST_AND_FOUND_MANAGE: 'LOST_AND_FOUND_MANAGE',
    LOST_AND_FOUND_MANAGER: 'LOST_AND_FOUND_MANAGER',
    CHECKLIST_READ: 'CHECKLIST_READ',
    CHECKLIST_MANAGE: 'CHECKLIST_MANAGE',
    CHECKLIST_MANAGER: 'CHECKLIST_MANAGER',
    TEST_CATALOG_VIEW: 'TEST_CATALOG_VIEW',
    TEST_CATALOG_EDIT: 'TEST_CATALOG_EDIT',
    TEST_CONFIGURE: 'TEST_CONFIGURE',
    TEST_RESULT_READ: 'TEST_RESULT_READ',
    TEST_REVIEW: 'TEST_REVIEW',
    TEST_MANAGER: 'TEST_MANAGER',
    PROTOCOL_TESTER: 'PROTOCOL_TESTER',
    PROTOCOL_CREATE: 'PROTOCOL_CREATE',
    PROTOCOL_CONFIGURE: 'PROTOCOL_CONFIGURE',
    PROTOCOL_MANAGER: 'PROTOCOL_MANAGER',
    BOARD_USE: 'BOARD_USE',
    BOARD_EDIT: 'BOARD_EDIT',
    BOARD_FEDERATE: 'BOARD_FEDERATE',
    BOARD_MANAGER: 'BOARD_MANAGER',
    PROCEDURE_READ: 'PROCEDURE_READ',
    PROCEDURE_EDIT: 'PROCEDURE_EDIT',
    PROCEDURE_MANAGER: 'PROCEDURE_MANAGER',
    PAGE_EDIT: 'PAGE_EDIT',
    PAGE_FORMS_VIEW: 'PAGE_FORMS_VIEW',
    PAGE_POLLS_VIEW: 'PAGE_POLLS_VIEW',
    PAGE_MANAGER: 'PAGE_MANAGER',
    KNOWLEDGE_EDIT: 'KNOWLEDGE_EDIT',
    KNOWLEDGE_FEDERATE: 'KNOWLEDGE_FEDERATE',
    KNOWLEDGE_MANAGER: 'KNOWLEDGE_MANAGER',
    STATION_LOOK_AND_FEEL: 'STATION_LOOK_AND_FEEL',
    STATION_GENERAL: 'STATION_GENERAL',
    STATION_MAIL: 'STATION_MAIL',
    STATION_FEDERATION: 'STATION_FEDERATION',
    STATION_MODULES: 'STATION_MODULES',
    STATION_IMPORT_EXPORT: 'STATION_IMPORT_EXPORT',
    STATION_STATISTICS: 'STATION_STATISTICS',
    STATION_MANAGER: 'STATION_MANAGER',
    STATION_ADMINISTRATOR: 'STATION_ADMINISTRATOR',
} as const satisfies Record<StationPermissionUnion, StationPermissionUnion>

export const StationModules = {
    INVENTORY: 'INVENTORY',
    NEWS: 'NEWS',
    EVENTS: 'EVENTS',
    ATTENDANCE: 'ATTENDANCE',
    FORMS: 'FORMS',
    LOST_AND_FOUND: 'LOST_AND_FOUND',
    WAITING_LIST: 'WAITING_LIST',
    QUIZ: 'QUIZ',
    KNOWLEDGE_BASE: 'KNOWLEDGE_BASE',
    TEST_PROTOCOL: 'TEST_PROTOCOL',
    BOARDS: 'BOARDS',
    PROCEDURES: 'PROCEDURES',
    DOCUMENTS: 'DOCUMENTS',
} as const satisfies Record<StationModule, StationModule>

/**
 * Audience selection shared by every restriction-capable feature. The restriction
 * editor speaks this shape; each feature maps it onto its own request payload.
 */
export interface RestrictionSelection {
    userTypes: StationUserTypeUnion[]
    groupIds: number[]
    tagIds: number[]
    memberIds: number[]
    mode: 'AND' | 'OR'
}
