#let data = json("data.json")

#let mark(checked) = if checked {
  box(width: 3.5mm, height: 3.5mm, stroke: 0.6pt + black, inset: 0pt)[
    #align(center + horizon)[#text(size: 8pt, weight: "bold")[X]]
  ]
} else {
  box(width: 3.5mm, height: 3.5mm, stroke: 0.6pt + black)
}

#set page(
  paper: "a4",
  flipped: true,
  margin: (top: 2.4cm, bottom: 1.6cm, x: 1.5cm),
  header: [
    #grid(
      columns: (auto, 1fr),
      column-gutter: 0.8em,
      align: (left + horizon, left + horizon),
      if data.hasLogo [ #image(data.logoFile, height: 1.1cm) ] else [],
      text(size: 11pt, weight: "bold")[#data.stationName],
    )
    #v(-0.4em)
    #line(length: 100%, stroke: 0.4pt + luma(180))
  ],
  footer: context {
    let page-num = here().page()
    let page-total = counter(page).final().first()
    align(center)[
      #text(size: 7pt, fill: luma(150))[
        Generated by #data.generatedBy on #data.generatedAt · Page #page-num of #page-total · #link(data.baseUrl)[#data.baseUrl]
      ]
    ]
  },
)
#set text(font: "Liberation Sans", size: 9pt)

#align(center)[
  #text(size: 14pt, weight: "bold")[#data.checklistName]
]

#if data.checklistDescription != "" [
  #v(0.2em)
  #align(center)[
    #text(size: 10pt, fill: luma(100))[#data.checklistDescription]
  ]
]

#v(0.8em)

#let col-widths = (auto,)
#for _ in data.columns {
  col-widths = col-widths + (1fr,)
}

#table(
  columns: col-widths,
  stroke: 0.5pt + luma(180),
  inset: 5pt,
  align: (left + horizon,) + data.columns.map(_ => left + horizon),
  table.cell(fill: luma(230))[*Member*],
  ..for col in data.columns {
    (table.cell(fill: luma(230))[*#col*],)
  },
  ..for row in data.rows {
    let cells = (align(left)[#row.name],)
    for cell in row.cells {
      let content = if cell.note != "" [
        #grid(
          columns: (auto, 1fr),
          column-gutter: 0.4em,
          align: (left + horizon, left + horizon),
          mark(cell.checked),
          text(size: 8pt)[#cell.note],
        )
      ] else [
        #mark(cell.checked)
      ]
      cells = cells + (content,)
    }
    cells
  },
)
