#let data = json("data.json")

#set page(
  paper: "a4",
  margin: (top: 2.4cm, bottom: 1.6cm, x: 2cm),
  header: [
    #grid(
      columns: (auto, 1fr),
      column-gutter: 0.8em,
      align: (left + horizon, left + horizon),
      if data.hasLogo [ #image(data.logoFile, height: 1.1cm) ] else [],
      text(size: 11pt, weight: "bold")[#data.stationName],
    )
    #v(-0.4em)
    #line(length: 100%, stroke: 0.4pt + luma(180))
  ],
  footer: context {
    let page-num = here().page()
    let page-total = counter(page).final().first()
    align(center)[
      #text(size: 7pt, fill: luma(150))[
        Generated by #data.generatedBy on #data.generatedAt · Page #page-num of #page-total · #link(data.baseUrl)[#data.baseUrl]
      ]
    ]
  },
)
#set text(font: "Liberation Sans", size: 10pt)
#set par(justify: false, leading: 0.65em)

#align(center)[
  #text(size: 14pt, weight: "bold")[#data.fileName]
]

#if data.fileDescription != "" [
  #v(0.2em)
  #align(center)[
    #text(size: 10pt, fill: luma(100))[#data.fileDescription]
  ]
]

#v(1em)

#for textLine in data.lines {
  if textLine == "" {
    v(0.6em)
  } else {
    block(width: 100%, below: 0.35em)[#textLine]
  }
}
