/*
 *     SPDX-License-Identifier: AGPL-3.0-only
 *
 *     Copyright (C) RainbowDashLabs and Contributor
 */
import {createApp} from 'vue'
import './style.css'
import App from './App.vue'
import router from './router'
import i18n from './i18n'

import {library} from '@fortawesome/fontawesome-svg-core'
import {FontAwesomeIcon} from '@fortawesome/vue-fontawesome'
import {
    faArrowRight,
    faAsterisk,
    faBan,
    faBars,
    faBell,
    faBold,
    faBoxesStacked,
    faBoxOpen,
    faBuilding,
    faCalendarDays,
    faCalendarPlus,
    faChartLine,
    faCheck,
    faCheckDouble,
    faChevronDown,
    faChevronLeft,
    faChevronRight,
    faChevronUp,
    faCircleCheck,
    faCircleInfo,
    faClipboardCheck,
    faClipboardList,
    faClipboardUser,
    faCode,
    faClockRotateLeft,
    faComment,
    faCopy,
    faDownload,
    faEye,
    faFileCode,
    faFileExport,
    faFire,
    faFolderPlus,
    faGauge,
    faGear,
    faGears,
    faGlobe,
    faGripVertical,
    faHashtag,
    faHeading,
    faHighlighter,
    faHouse,
    faIdCard,
    faItalic,
    faLayerGroup,
    faAlignCenter,
    faAlignLeft,
    faAlignRight,
    faLink,
    faLinkSlash,
    faList,
    faListOl,
    faListUl,
    faLock,
    faMedal,
    faMinus,
    faNewspaper,
    faMobileScreen,
    faMoon,
    faParagraph,
    faPen,
    faPenToSquare,
    faPeopleGroup,
    faPhone,
    faPlus,
    faQuoteLeft,
    faRainbow,
    faRightFromBracket,
    faRotate,
    faScissors,
    faShield,
    faShuffle,
    faSliders,
    faSort,
    faSortDown,
    faSortUp,
    faSpinner,
    faStrikethrough,
    faSun,
    faTableColumns,
    faTrash,
    faTriangleExclamation,
    faUnderline,
    faUpload,
    faUser,
    faUserCheck,
    faUserPlus,
    faUserSlash,
    faUsers,
    faUsersGear,
    faXmark,
    faXmarkCircle,
    faCircleQuestion,
    faFilter,
    faTags,
    faSquarePollVertical,
    faStar,
    faHeart,
    faThumbsUp,
    faGripLines,
    faLocationDot,
    faCamera,
    faToggleOn,
    faArrowRightArrowLeft,
    faPuzzlePiece,
    faPalette,
    faBook,
    faServer,
    faDatabase,
    faEnvelope,
    faArrowDown,
    faUserGear,
    faCalendar,
    faChartBar,
    faChartPie,
    faClock,
    faHand,
    faHandHolding,
    faImage,
    faPaperPlane,
    faPlug,
    faTag,
    faUmbrellaBeach,
    faUserShield,
    faUserTie,
    faListCheck,
    faCircleHalfStroke,
    faSquare,
    faSquareCheck,
    faGraduationCap,
    faBrain,
    faFileLines,
    faFilePdf,
    faFileImport,
    faFlask,
    faPlay,
    faBookOpen,
    faFolder,
    faFolderOpen,
    faFile,
    faMagnifyingGlass,
    faHandshake,
    faCalendarXmark,
} from '@fortawesome/free-solid-svg-icons'
import {
    faGithub,
    faWindows,
    faApple,
    faLinux,
    faAndroid,
    faChrome,
    faFirefoxBrowser,
    faSafari,
    faEdge,
    faOpera,
    faYoutube,
} from '@fortawesome/free-brands-svg-icons'
import {initTokenRefresh} from '@/api/client'

library.add(faSun, faMoon, faCheck, faXmark, faXmarkCircle, faSpinner, faCircleInfo, faCircleCheck, faTriangleExclamation, faDownload, faUpload, faTrash, faPen, faLock, faRightFromBracket, faBars, faGauge, faChevronDown, faChevronRight, faHouse, faChartLine, faShield, faBuilding, faGears, faUsers, faUserPlus, faList, faLayerGroup, faBoxesStacked, faBoxOpen, faClipboardUser, faCalendarPlus, faClockRotateLeft, faClipboardCheck, faUsersGear, faPlus, faChevronLeft, faChevronUp, faGripVertical, faCopy, faBell, faPhone, faMobileScreen, faIdCard, faHashtag, faFire, faMedal, faRainbow, faCalendarDays, faPenToSquare, faFolderPlus, faClipboardList, faUser, faSort, faSortUp, faSortDown, faAsterisk, faEye, faLink, faTableColumns, faBan, faComment, faCheckDouble, faMinus, faRotate, faScissors, faNewspaper, faGear, faPeopleGroup, faArrowRight, faFileExport, faGithub, faWindows, faApple, faLinux, faAndroid, faChrome, faFirefoxBrowser, faSafari, faEdge, faOpera, faGlobe, faUserSlash, faUserCheck, faCircleQuestion, faFilter, faTags, faSquarePollVertical, faStar, faHeart, faThumbsUp, faGripLines, faLocationDot, faCamera, faToggleOn, faArrowRightArrowLeft, faPuzzlePiece, faBook, faServer, faDatabase, faEnvelope, faArrowDown, faUserGear, faCalendar, faChartBar, faChartPie, faClock, faHand, faImage, faPaperPlane, faPlug, faTag, faUmbrellaBeach, faUserShield, faUserTie, faListCheck, faSliders, faCircleHalfStroke, faPalette, faSquare, faSquareCheck, faGraduationCap, faBrain, faFileLines, faFilePdf, faFileImport, faFlask, faShuffle, faPlay, faBookOpen, faFolder, faFolderOpen, faFile, faMagnifyingGlass, faYoutube, faBold, faItalic, faUnderline, faStrikethrough, faCode, faListUl, faListOl, faQuoteLeft, faFileCode, faParagraph, faHeading, faHighlighter, faLinkSlash, faAlignLeft, faAlignCenter, faAlignRight, faHandshake, faHandHolding, faCalendarXmark)

import {useTheme} from '@/composables/useTheme'

initTokenRefresh()
useTheme().initFromLocalStorage()

createApp(App)
    .component('font-awesome-icon', FontAwesomeIcon)
    .use(router)
    .use(i18n)
    .mount('#app')
