INSERT INTO ember_schema.station_permission (name)
VALUES ('DOCUMENT_TEMPLATE_EDIT')
ON CONFLICT (name) DO NOTHING;

ALTER TABLE ember_schema.member_manager
    ADD COLUMN position   INTEGER     NOT NULL DEFAULT 0,
    ADD COLUMN created_at TIMESTAMPTZ NULL,
    ADD COLUMN created_by INTEGER     NULL REFERENCES ember_schema.station_member (id) ON DELETE SET NULL;

UPDATE ember_schema.member_manager mm
SET position = ranked.position
FROM (SELECT manager_id,
             managed_id,
             ROW_NUMBER() OVER (PARTITION BY managed_id ORDER BY manager_id) - 1 AS position
      FROM ember_schema.member_manager) ranked
WHERE ranked.manager_id = mm.manager_id
  AND ranked.managed_id = mm.managed_id;

ALTER TABLE ember_schema.member_manager
    ALTER COLUMN created_at SET DEFAULT now();

COMMENT ON COLUMN ember_schema.member_manager.position IS
    'The order of the guardians of one member, counted from 0. The guardian at 0 is the first guardian, which documents name as guardian 1.';
COMMENT ON COLUMN ember_schema.member_manager.created_at IS
    'When the guardian was linked to the member. NULL for links made before this was recorded.';
COMMENT ON COLUMN ember_schema.member_manager.created_by IS
    'The member who linked the guardian. NULL where nobody did (an import, a waiting list, a link made before this was recorded) or once they are gone.';

CREATE TABLE IF NOT EXISTS ember_schema.document_template
(
    id                         SERIAL PRIMARY KEY,
    station_id                 INTEGER     NOT NULL REFERENCES ember_schema.station (id) ON DELETE CASCADE,
    kind                       TEXT        NOT NULL DEFAULT 'LETTER' CHECK (kind IN ('LETTER')),
    name                       TEXT        NOT NULL,
    title_pattern              TEXT        NOT NULL,
    file_name_pattern          TEXT        NOT NULL,
    tags                       TEXT[]      NOT NULL DEFAULT '{}',
    hidden                     BOOLEAN     NOT NULL DEFAULT FALSE,
    keep_on_archive            BOOLEAN     NOT NULL DEFAULT FALSE,
    legal                      BOOLEAN     NOT NULL DEFAULT FALSE,
    self_service               BOOLEAN     NOT NULL DEFAULT FALSE,
    self_service_cooldown_days INTEGER     NOT NULL DEFAULT 30 CHECK (self_service_cooldown_days >= 0),
    restriction_mode           TEXT        NOT NULL DEFAULT 'AND' CHECK (restriction_mode IN ('AND', 'OR')),
    pronoun_field_id           INTEGER     NULL REFERENCES ember_schema.profile_field (id) ON DELETE SET NULL,
    pronoun_mapping            JSONB       NULL,
    version                    INTEGER     NOT NULL DEFAULT 1,
    created_at                 TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by                 INTEGER     NULL REFERENCES ember_schema.station_member (id) ON DELETE SET NULL,
    updated_at                 TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by                 INTEGER     NULL REFERENCES ember_schema.station_member (id) ON DELETE SET NULL,
    archived_at                TIMESTAMPTZ NULL
);

CREATE INDEX IF NOT EXISTS idx_document_template_station ON ember_schema.document_template (station_id);

COMMENT ON TABLE ember_schema.document_template IS
    'A template a station turns into a PDF for one member at a time. Never deleted, only archived, so every generated document keeps pointing at the template it came from.';
COMMENT ON COLUMN ember_schema.document_template.id IS 'Auto-generated primary key.';
COMMENT ON COLUMN ember_schema.document_template.station_id IS 'The station that owns the template.';
COMMENT ON COLUMN ember_schema.document_template.kind IS
    'What the template is made of: LETTER, a letterhead and a body written in Ember (document_template_letter).';
COMMENT ON COLUMN ember_schema.document_template.name IS 'What the template is called in the list of templates.';
COMMENT ON COLUMN ember_schema.document_template.title_pattern IS
    'The title a generated document is filed under, with placeholders such as {{today}} filled in when it is generated.';
COMMENT ON COLUMN ember_schema.document_template.file_name_pattern IS
    'The file name a generated document is filed under, with placeholders filled in when it is generated. The file always ends in .pdf.';
COMMENT ON COLUMN ember_schema.document_template.tags IS
    'The names of the document tags a generated document is filed with. Tags missing at the station are created when a document is filed.';
COMMENT ON COLUMN ember_schema.document_template.hidden IS
    'Whether a document generated by a manager is hidden from the member it names. Documents a member generates through self service are never hidden.';
COMMENT ON COLUMN ember_schema.document_template.keep_on_archive IS
    'Whether a generated document outlasts the membership of the member it names.';
COMMENT ON COLUMN ember_schema.document_template.legal IS
    'Whether the template makes a legal document. A legal template uses official names only and may not use the name a member is called by.';
COMMENT ON COLUMN ember_schema.document_template.self_service IS
    'Whether members of the audience may generate the document for themselves, and guardians for the members in their care.';
COMMENT ON COLUMN ember_schema.document_template.self_service_cooldown_days IS
    'How many days must pass before a member may generate the document again through self service. 0 means no wait.';
COMMENT ON COLUMN ember_schema.document_template.restriction_mode IS
    'AND or OR, how the parts of document_template_restriction combine.';
COMMENT ON COLUMN ember_schema.document_template.pronoun_field_id IS
    'The choice profile field the pronouns of the template follow. NULL where the pronouns always use the first name, also once that field was deleted.';
COMMENT ON COLUMN ember_schema.document_template.pronoun_mapping IS
    'Which pronoun (ER, SIE or NAME) each answer of the pronoun field stands for, and the one used for an empty or unmapped answer. NULL where the template names no pronoun field.';
COMMENT ON COLUMN ember_schema.document_template.version IS
    'Counts up with every change, so the generation log says which state of the template a document came from.';
COMMENT ON COLUMN ember_schema.document_template.created_at IS 'When the template was created.';
COMMENT ON COLUMN ember_schema.document_template.created_by IS 'The member who created the template. NULL once they are gone.';
COMMENT ON COLUMN ember_schema.document_template.updated_at IS 'When the template was last changed.';
COMMENT ON COLUMN ember_schema.document_template.updated_by IS 'The member who last changed the template. NULL once they are gone.';
COMMENT ON COLUMN ember_schema.document_template.archived_at IS
    'When the template was archived. An archived template generates nothing more and stays for the documents generated from it. NULL while in use.';

CREATE TABLE IF NOT EXISTS ember_schema.document_template_restriction
(
    id          SERIAL PRIMARY KEY,
    template_id INT NOT NULL REFERENCES ember_schema.document_template (id) ON DELETE CASCADE,
    user_type   TEXT,
    group_id    INT REFERENCES ember_schema.member_group (id) ON DELETE CASCADE,
    tag_id      INT REFERENCES ember_schema.user_tag (id) ON DELETE CASCADE,
    member_id   INT REFERENCES ember_schema.station_member (id) ON DELETE CASCADE,
    CHECK (num_nonnulls(user_type, group_id, tag_id, member_id) = 1)
);

CREATE INDEX IF NOT EXISTS idx_document_template_restriction_template
    ON ember_schema.document_template_restriction (template_id);

COMMENT ON TABLE ember_schema.document_template_restriction IS
    'Who may generate a self service template for themselves. Empty means every member. Shaped like event_restriction.';
COMMENT ON COLUMN ember_schema.document_template_restriction.id IS 'Auto-generated primary key.';
COMMENT ON COLUMN ember_schema.document_template_restriction.template_id IS 'References the document template.';
COMMENT ON COLUMN ember_schema.document_template_restriction.user_type IS
    'Required user type. Exactly one of user_type/group_id/tag_id/member_id must be set.';
COMMENT ON COLUMN ember_schema.document_template_restriction.group_id IS 'Required group membership.';
COMMENT ON COLUMN ember_schema.document_template_restriction.tag_id IS 'Required tag.';
COMMENT ON COLUMN ember_schema.document_template_restriction.member_id IS
    'Specific member (always OR-connected, bypasses AND/OR mode).';

CREATE TABLE IF NOT EXISTS ember_schema.document_template_letter
(
    template_id   INTEGER PRIMARY KEY REFERENCES ember_schema.document_template (id) ON DELETE CASCADE,
    letterhead    JSONB   NOT NULL,
    body_markdown TEXT    NOT NULL,
    page          JSONB   NOT NULL
);

COMMENT ON TABLE ember_schema.document_template_letter IS
    'The content of a letter template: its letterhead, its body and its page.';
COMMENT ON COLUMN ember_schema.document_template_letter.template_id IS 'References the document template.';
COMMENT ON COLUMN ember_schema.document_template_letter.letterhead IS
    'The header and the footer, each a row of up to three cells. A cell is empty, a picture from the media library by its content hash, the station logo, or a short text with placeholders, aligned left, centre or right.';
COMMENT ON COLUMN ember_schema.document_template_letter.body_markdown IS
    'The body as markdown, with placeholders written as {{key}}. Pictures point at the station media library.';
COMMENT ON COLUMN ember_schema.document_template_letter.page IS
    'The page margins in millimetres and the body font size in points. The paper is always A4.';

CREATE TABLE IF NOT EXISTS ember_schema.document_generation
(
    id               SERIAL PRIMARY KEY,
    station_id       INTEGER     NOT NULL REFERENCES ember_schema.station (id) ON DELETE CASCADE,
    template_id      INTEGER     NOT NULL REFERENCES ember_schema.document_template (id) ON DELETE CASCADE,
    template_version INTEGER     NOT NULL,
    member_id        INTEGER     NULL REFERENCES ember_schema.station_member (id) ON DELETE SET NULL,
    generated_by     INTEGER     NULL REFERENCES ember_schema.station_member (id) ON DELETE SET NULL,
    generated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    self_service     BOOLEAN     NOT NULL,
    document_id      INTEGER     NULL REFERENCES ember_schema.member_document (id) ON DELETE SET NULL,
    file_sha256      TEXT        NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_document_generation_template_member
    ON ember_schema.document_generation (template_id, member_id, generated_at);
CREATE INDEX IF NOT EXISTS idx_document_generation_station ON ember_schema.document_generation (station_id);

COMMENT ON TABLE ember_schema.document_generation IS
    'Every document generated from a template: which template and which state of it, about whom, by whom, when, and the file that came out.';
COMMENT ON COLUMN ember_schema.document_generation.id IS 'Auto-generated primary key.';
COMMENT ON COLUMN ember_schema.document_generation.station_id IS 'The station the document was filed at.';
COMMENT ON COLUMN ember_schema.document_generation.template_id IS 'The template the document was generated from.';
COMMENT ON COLUMN ember_schema.document_generation.template_version IS
    'The version of the template at the time, which a later change of the template does not touch.';
COMMENT ON COLUMN ember_schema.document_generation.member_id IS
    'The member the document is about and was filed for. NULL once that member was deleted.';
COMMENT ON COLUMN ember_schema.document_generation.generated_by IS
    'The member who generated it: a manager, the member themselves or their guardian. NULL once they are gone.';
COMMENT ON COLUMN ember_schema.document_generation.generated_at IS 'When the document was generated.';
COMMENT ON COLUMN ember_schema.document_generation.self_service IS
    'Whether it was generated through self service, which is what the cooldown of the template counts.';
COMMENT ON COLUMN ember_schema.document_generation.document_id IS
    'The member document the file was filed as. NULL once that document was deleted.';
COMMENT ON COLUMN ember_schema.document_generation.file_sha256 IS
    'The SHA-256 of the generated file as lowercase hex, which ties the log to the exact bytes filed.';

CREATE TABLE IF NOT EXISTS ember_schema.document_generation_subject
(
    generation_id INTEGER NOT NULL REFERENCES ember_schema.document_generation (id) ON DELETE CASCADE,
    member_id     INTEGER NOT NULL REFERENCES ember_schema.station_member (id) ON DELETE CASCADE,
    role          TEXT    NOT NULL CHECK (role IN ('MEMBER', 'GUARDIAN')),
    PRIMARY KEY (generation_id, member_id)
);

CREATE INDEX IF NOT EXISTS idx_document_generation_subject_member
    ON ember_schema.document_generation_subject (member_id);

COMMENT ON TABLE ember_schema.document_generation_subject IS
    'Every person whose data went into a generated document: the member it is about and the guardians it names.';
COMMENT ON COLUMN ember_schema.document_generation_subject.generation_id IS 'References the generated document.';
COMMENT ON COLUMN ember_schema.document_generation_subject.member_id IS 'A person whose data went into the document.';
COMMENT ON COLUMN ember_schema.document_generation_subject.role IS
    'MEMBER for the member the document is about, GUARDIAN for a guardian whose data it holds.';
