-- Placeholder.
--
-- This number belongs to a change developed on another branch. It is held open here so the branch
-- that carries patch 39 runs on its own: the updater walks the numbers in order and stops at the
-- first one it cannot find, silently, leaving the database short of every patch above the gap.
--
-- The branch that owns this number replaces the file wholesale.
