/*
 *     SPDX-License-Identifier: AGPL-3.0-only
 *
 *     Copyright (C) RainbowDashLabs and Contributor
 */
package dev.chojo.ember.feature.page.service;

import dev.chojo.ember.feature.station.repository.StationRepository;
import jakarta.inject.Inject;
import jakarta.inject.Singleton;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.HexFormat;
import java.util.Optional;
import java.util.UUID;
import java.util.stream.Stream;

/**
 * On-disk storage for files uploaded against pages (images today, PDFs/audio/downloads in the
 * future), partitioned per station and keyed by the file's SHA-256 hash.
 *
 * <p>Layout (concept §11.1):
 * {@code data/page-files/<stationUuid>/<contentHash>/orig.<ext>} for the bytes,
 * {@code .../<contentHash>/.content-type} for the MIME type sidecar, and width-keyed
 * variants {@code .../<contentHash>/w<width>.<ext|webp>} generated by
 * {@link PageImageVariantService}. The station UUID prefix isolates files between stations
 * while the hash key inside enables dedup within a station — uploading the same file twice
 * for the same station reuses the existing on-disk copy.
 *
 * <p>Backward compatibility: pre-phase-5 uploads landed at the flat path
 * {@code data/page-files/<stationUuid>/<contentHash>} with a sibling
 * {@code <contentHash>.content-type} file. The first read of such a file
 * {@linkplain #migrateLegacyLayout migrates} it into the new directory layout, so the
 * directory shape converges without a global one-shot migration.
 */
@Singleton
public class PageFileStorageService {
    private static final Logger log = LoggerFactory.getLogger(PageFileStorageService.class);
    private static final String ORIG_PREFIX = "orig";
    private static final String CONTENT_TYPE_FILE = ".content-type";
    private final Path baseDir = Path.of("data", "page-files");
    private final StationRepository stationRepository;

    @Inject
    public PageFileStorageService(StationRepository stationRepository) {
        this.stationRepository = stationRepository;
    }

    /** Hex SHA-256 of the given bytes (lowercase). */
    public static String hash(byte[] data) {
        try {
            var digest = MessageDigest.getInstance("SHA-256").digest(data);
            return HexFormat.of().formatHex(digest);
        } catch (NoSuchAlgorithmException e) {
            throw new IllegalStateException("SHA-256 unavailable", e);
        }
    }

    /**
     * Persists the original bytes for a (station, hash) pair. Idempotent — calling twice with
     * the same hash is a semantic no-op because the bytes are identical by definition. Also
     * writes the {@code .content-type} sidecar inside the hash directory.
     */
    public void store(int stationId, String contentHash, byte[] data, String contentType) throws IOException {
        Path dir = hashDir(stationId, contentHash);
        Files.createDirectories(dir);
        Path original = dir.resolve(ORIG_PREFIX + "." + extensionFor(contentType));
        cleanupLegacyOriginals(dir, original.getFileName().toString());
        Files.write(original, data);
        if (contentType != null) {
            Files.writeString(dir.resolve(CONTENT_TYPE_FILE), contentType);
        }
    }

    /**
     * Reads the original bytes + MIME type for a (station, hash). Migrates legacy flat-file
     * uploads into the new directory layout on first read. Returns {@link Optional#empty()}
     * if the file is missing or unreadable.
     */
    public Optional<FileData> read(int stationId, String contentHash) {
        migrateLegacyLayout(stationId, contentHash);
        return readVariant(stationId, contentHash, ORIG_PREFIX, null);
    }

    /**
     * Reads a single named variant from the (station, hash) directory.
     *
     * <p>{@code baseName} is the file name without extension (e.g. {@code "orig"},
     * {@code "w512"}). {@code extension} pins a specific format ({@code "webp"},
     * {@code "jpg"}, …) — pass {@code null} to accept any extension, which is the right
     * choice when reading the original whose on-disk format is whatever the user uploaded.
     *
     * <p>Returns empty if no matching file exists; the caller picks a fallback.
     */
    public Optional<FileData> readVariant(int stationId, String contentHash, String baseName, String extension) {
        Path dir = hashDir(stationId, contentHash);
        if (!Files.isDirectory(dir)) return Optional.empty();
        Path match = findVariant(dir, baseName, extension);
        if (match == null) return Optional.empty();
        try {
            byte[] data = Files.readAllBytes(match);
            String contentType = contentTypeFor(dir, match);
            return Optional.of(new FileData(data, contentType));
        } catch (IOException e) {
            log.error(
                    "Failed to read page image station={} hash={} base={} ext={}",
                    stationId,
                    contentHash,
                    baseName,
                    extension,
                    e);
            return Optional.empty();
        }
    }

    /**
     * Writes a single variant blob into the (station, hash) directory under
     * {@code <variantName>.<extension>}. Used by {@link PageImageVariantService}; the rest of
     * the application calls {@link #store} for originals only.
     */
    public void storeVariant(int stationId, String contentHash, String variantName, String extension, byte[] data)
            throws IOException {
        Path dir = hashDir(stationId, contentHash);
        Files.createDirectories(dir);
        Files.write(dir.resolve(variantName + "." + extension), data);
    }

    /**
     * Returns the on-disk path for the hash directory. Visible for tests and the variant
     * service; not part of the public read API.
     */
    public Path hashDir(int stationId, String contentHash) {
        UUID uid = stationRepository.resolveUid(stationId);
        return baseDir.resolve(uid.toString()).resolve(contentHash);
    }

    /**
     * Deletes everything under the (station, hash) directory — original, all variants, and the
     * content-type sidecar. Caller is responsible for ensuring no other DB rows reference the
     * same hash within the same station.
     */
    public void delete(int stationId, String contentHash) {
        Path dir = hashDir(stationId, contentHash);
        deleteDirectoryQuietly(dir);
        Path legacy = baseDir.resolve(stationRepository.resolveUid(stationId).toString())
                .resolve(contentHash);
        deleteQuietly(legacy);
        deleteQuietly(legacy.resolveSibling(contentHash + ".content-type"));
    }

    private Path findVariant(Path dir, String baseName, String extension) {
        if (extension != null && !extension.isEmpty()) {
            Path direct = dir.resolve(baseName + "." + extension);
            return Files.isRegularFile(direct) ? direct : null;
        }
        try (Stream<Path> entries = Files.list(dir)) {
            var candidates = entries.filter(Files::isRegularFile)
                    .filter(p -> {
                        String name = p.getFileName().toString();
                        int dot = name.lastIndexOf('.');
                        String base = dot < 0 ? name : name.substring(0, dot);
                        return base.equals(baseName);
                    })
                    .toList();
            if (candidates.isEmpty()) return null;
            for (Path p : candidates) {
                if (!p.getFileName().toString().endsWith(".webp")) return p;
            }
            return candidates.getFirst();
        } catch (IOException e) {
            log.warn("Failed to list variant directory {}", dir, e);
            return null;
        }
    }

    private void migrateLegacyLayout(int stationId, String contentHash) {
        Path target = hashDir(stationId, contentHash);
        if (Files.isDirectory(target)) return;
        if (!Files.isRegularFile(target)) return;
        Path stationDir = target.getParent();
        Path legacyType = stationDir.resolve(contentHash + ".content-type");
        String contentType = "application/octet-stream";
        try {
            if (Files.exists(legacyType)) {
                contentType = Files.readString(legacyType).trim();
            }
            Path scratch = stationDir.resolve("." + contentHash + ".tmp");
            Files.move(target, scratch, StandardCopyOption.REPLACE_EXISTING);
            Files.createDirectories(target);
            Files.move(
                    scratch,
                    target.resolve(ORIG_PREFIX + "." + extensionFor(contentType)),
                    StandardCopyOption.REPLACE_EXISTING);
            Files.writeString(target.resolve(CONTENT_TYPE_FILE), contentType);
            deleteQuietly(legacyType);
            log.info("Migrated legacy page-file station={} hash={} to directory layout", stationId, contentHash);
        } catch (IOException e) {
            log.warn("Failed to migrate legacy page-file station={} hash={}", stationId, contentHash, e);
        }
    }

    private void cleanupLegacyOriginals(Path dir, String keepFileName) {
        try (Stream<Path> entries = Files.list(dir)) {
            for (Path p : entries.filter(Files::isRegularFile).toList()) {
                String name = p.getFileName().toString();
                if (name.startsWith(ORIG_PREFIX + ".") && !name.equals(keepFileName)) {
                    deleteQuietly(p);
                }
            }
        } catch (IOException e) {
            log.debug("Failed to enumerate {} during cleanup; new write wins on next read", dir, e);
        }
    }

    private String contentTypeFor(Path dir, Path file) throws IOException {
        Path sidecar = dir.resolve(CONTENT_TYPE_FILE);
        String name = file.getFileName().toString();
        int dot = name.lastIndexOf('.');
        String ext = dot < 0 ? "" : name.substring(dot + 1).toLowerCase(java.util.Locale.ROOT);
        if (ext.equals("webp")) return "image/webp";
        if (Files.exists(sidecar)) return Files.readString(sidecar).trim();
        return mimeForExtension(ext);
    }

    private static String mimeForExtension(String ext) {
        return switch (ext) {
            case "jpg", "jpeg" -> "image/jpeg";
            case "png" -> "image/png";
            case "gif" -> "image/gif";
            case "webp" -> "image/webp";
            case "svg" -> "image/svg+xml";
            case "pdf" -> "application/pdf";
            default -> "application/octet-stream";
        };
    }

    private static String extensionFor(String mimeType) {
        if (mimeType == null) return "bin";
        return switch (mimeType.toLowerCase(java.util.Locale.ROOT)) {
            case "image/jpeg" -> "jpg";
            case "image/png" -> "png";
            case "image/gif" -> "gif";
            case "image/webp" -> "webp";
            case "image/svg+xml" -> "svg";
            case "application/pdf" -> "pdf";
            default -> "bin";
        };
    }

    private void deleteQuietly(Path path) {
        try {
            Files.deleteIfExists(path);
        } catch (IOException e) {
            log.warn("Failed to delete {}", path, e);
        }
    }

    private void deleteDirectoryQuietly(Path dir) {
        if (!Files.isDirectory(dir)) return;
        try (Stream<Path> entries = Files.walk(dir)) {
            entries.sorted(java.util.Comparator.reverseOrder()).forEach(this::deleteQuietly);
        } catch (IOException e) {
            log.warn("Failed to delete directory {}", dir, e);
        }
    }

    /**
     * The bytes + MIME type returned by {@link #read}. {@code contentType} is derived from
     * the variant's extension (WebP always reports {@code image/webp}; the original falls back
     * to the stored sidecar) so callers can set the {@code Content-Type} header verbatim.
     */
    public record FileData(byte[] data, String contentType) {}
}
